name: Deno Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            dist
            .nuxt
            node_modukes
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install deps
        run: npm i
      - name: Nuxt build
        run: npm run generate
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: liberluna # the name of the project on Deno Deploy
          entrypoint: deno-server.js # the entrypoint to deploy
